# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3865b710c75fc2695073b0299b657d44a59f6d246aff5498e063c0e6108cdf3742707d0ce1bec673f1c8b0884de63606963b21c69997b82c0677ceedbad1c6c

test:
  secret_key_base: 2d8035fe1dd1f1c206d699cbdd292d0d7da8576ee01ccbb5d8d83b39971b8faa9768a7302d9e1589374e095d9177ce9c410ac99f2cb23d6dc7d33c331e8b082c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
